package cscie99.team2.lingolearn.server.confuser;

import static org.junit.Assert.*;

import java.io.IOException;
import java.util.List;

import org.junit.Before;
import org.junit.Test;

import cscie99.team2.lingolearn.shared.Card;
import cscie99.team2.lingolearn.shared.error.ConfuserException;

/**
 * This class tests to make sure that the values being generated by the confuser
 * algorithm are valid.
 */
public class ConfuserTest {
	// The confuser instance to use for tests
	private static Confuser confuser;

	/**
	 * Make sure the confuser algorithm code is using the correct data.
	 */
	@Before
	public void setUp() {
		ConfuserTest.confuser = new Confuser();
	}

	/**
	 * Test to make sure that we can extend kanji with valid hiragana.
	 */
	@Test
	public void kanjiBoundriesTest() {
		// Test to make sure 食べ難い (difficult to eat) is extended correctly
		Card card = new Card();
		card.setKanji("食べ難い");
		card.setHiragana("たべにくい");
		List<String> results = confuser.getKanjiBoundries(card);
		assertEquals(1, results.size());
		assertEquals("食べ難くい", results.get(0));

		// Test to make sure 青い (blue) is extended correctly
		card = new Card();
		card.setKanji("青い");
		card.setHiragana("あおい");
		results = confuser.getKanjiBoundries(card);
		assertEquals(1, results.size());
		assertEquals("青おい", results.get(0));

		// Test to make sure 話す (to speak) is extended correctly
		card = new Card();
		card.setKanji("話す");
		card.setHiragana("はなす");
		results = confuser.getKanjiBoundries(card);
		assertEquals(1, results.size());
		assertEquals("話なす", results.get(0));

		// Test to make sure お結び (rice ball) is extended correctly
		card = new Card();
		card.setKanji("お結び");
		card.setHiragana("おむすび");
		results = confuser.getKanjiBoundries(card);
		assertEquals(1, results.size());
		assertEquals("お結すび", results.get(0));

		// Test to make sure the する (to do) suffix is not extended
		card = new Card();
		card.setKanji("勉強する");
		card.setHiragana("べんきょうする");
		results = confuser.getKanjiBoundries(card);
		assertEquals(0, results.size());
	}
	
	/**
	 * Test to make sure kanji substitution works correctly.
	 */
	@Test
	public void kanjiSubsitutionTest() throws ConfuserException, IOException {
		// TODO Get more unit tests for this function, we need one where the 
		// TODO replacement kanji is in the middle and one were the replacement
		// TODO kanji is at the end
		
		// Test to make sure 介護 (nursing) is manipulated correctly, in this
		// case, the first kanji will be replaced
		String[] expected = new String[] { "价護", "堺護", "界護", "畍護", "疥護", "芥護"};
		List<String> results = confuser.getKanjiSubsitution("介護");
		assertEquals(expected.length, results.size());
		for (String phrase : expected) {
			assertEquals(true, results.contains(phrase));
		}
		
		// Test to make sure 党議拘束 (compulsory adherence to a party decision; 
		// restrictions on party debate) is manipulated correctly in this case,
		// the second kanji will be replaced
		expected = new String[] { "党儀拘束", "党嶬拘束", "党犠拘束", "党礒拘束", "党義拘束", "党艤拘束", "党蟻拘束"};
		results = confuser.getKanjiSubsitution("党議拘束");
		assertEquals(expected.length, results.size());
		for (String phrase : expected) {
			assertEquals(true, results.contains(phrase));
		}
	}

	/**
	 * Test to make sure vowels are elongated correctly for hiragana and
	 * katakana words.
	 */
	@Test
	public void vowelElongationTest() {
		fail("Not implimented");
	}

	/**
	 * Test to make sure the small tsu character (ッ) is being manipulated
	 * correctly.
	 */
	@Test
	public void smallTsuManipulation() {
		// Test to make sure ヒット (hit) is manipulated correctly
		List<String> results = confuser.getSmallTsuManiuplation("ヒット");
		assertEquals(1, results.size());
		assertEquals("ヒト", results.get(0));
		
		// Test to make sure ヒト  (person) is manipulated correctly
		results = confuser.getSmallTsuManiuplation("ヒト");
		assertEquals(1, results.size());
		assertEquals("ヒット", results.get(0));
	}

	/**
	 * Test to make sure the n character (ん, ン) is being manipulated correctly
	 * for hiragana and katakana.
	 */
	@Test
	public void nManipulation() {
		// Test to make sure テニス (tennis) is manipulated correctly
		List<String> results = confuser.getNManipulation("テニス");
		assertEquals(1, results.size());
		assertEquals("テンニス", results.get(0));
		
		// Test to make sure なのか (seven days) is manipulated correctly
		results = confuser.getNManipulation("なのか");
		assertEquals(1, results.size());
		assertEquals("なんのか", results.get(0));
		
		// Test to make sure こんなん  (stress) is manipulated correctly
		results = confuser.getNManipulation("こんなん");
		assertEquals(1, results.size());
		assertEquals("こなん", results.get(0));
	}
}
