package cscie99.team2.lingolearn.shared;

public enum SessionTypes {

	KANJI_TRANSLATION, 
	HIRAGANA_TRANSLATION,
	TRANSLATION_KANJI,
	TRANSLATION_HIRAGANA,
	KANJI_HIRAGANA,
	HIRAGANA_KANJI,
	CONFUSOR
	
}
